{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.simplix.cirrus",
    "module": "cirrus-velocity",
    "version": "3.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cirrus-velocity-3.0.0-SNAPSHOT.jar",
          "url": "cirrus-velocity-3.0.0-SNAPSHOT.jar",
          "size": 14498,
          "sha512": "74e9e1b03e58bd36aced0d46e23b38e5e2206cf5fa8340f37e234f1039a6966f5ecbb4efce48fe2793cb5508be0f9ceb1236d712fd4acdb162bb7eccad9dcb98",
          "sha256": "1dbdb88f92288a7c427308cf87ba3cac8071ff9ec1aeb7aa0c90e11787bf11dd",
          "sha1": "36a70f1a89bafbe87dc6dc0658cf4b3f10b1a189",
          "md5": "517461864cdb10ce996388dcdea4e2bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.simplix.cirrus",
          "module": "cirrus-api",
          "version": {
            "requires": "3.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "cirrus-velocity-3.0.0-SNAPSHOT.jar",
          "url": "cirrus-velocity-3.0.0-SNAPSHOT.jar",
          "size": 14498,
          "sha512": "74e9e1b03e58bd36aced0d46e23b38e5e2206cf5fa8340f37e234f1039a6966f5ecbb4efce48fe2793cb5508be0f9ceb1236d712fd4acdb162bb7eccad9dcb98",
          "sha256": "1dbdb88f92288a7c427308cf87ba3cac8071ff9ec1aeb7aa0c90e11787bf11dd",
          "sha1": "36a70f1a89bafbe87dc6dc0658cf4b3f10b1a189",
          "md5": "517461864cdb10ce996388dcdea4e2bf"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cirrus-velocity-3.0.0-SNAPSHOT-all.jar",
          "url": "cirrus-velocity-3.0.0-SNAPSHOT-all.jar",
          "size": 128854,
          "sha512": "4e4e05340c2975226e4552a756abbd279a2fc67c810ca4d2eef3a833dc20b27b7a92948073b69fa6b2a83bd1bca85bd24512dc2fec3a6f9dc46df83f61a5b330",
          "sha256": "95ab5620d8e37c3a862efa34e1f81fa780a4e9331c6e7ce8dc2f02b0e3d2b36f",
          "sha1": "81a1c6339ef9a049d39f5281781ed3ddf8e8253d",
          "md5": "46ff3d2fd37bbc5ab2e096f2d57b6b01"
        }
      ]
    }
  ]
}
